import { QuizQuestion, DragItem, ProtistaMatch } from './types';

export const QUIZ_DATA: QuizQuestion[] = [
  { id: 1, sentenceBefore: "Monera are called", hiddenWord: "Prokaryotic", sentenceAfter: "organisms because they lack a nucleus." },
  { id: 2, sentenceBefore: "Fungi differ from animals; they do not ingest food, they", hiddenWord: "Absorb", sentenceAfter: "it." },
  { id: 3, sentenceBefore: "Monocots usually have", hiddenWord: "Parallel", sentenceAfter: "veins in their leaves." },
  { id: 4, sentenceBefore: "Mitochondria are thought to have evolved from bacteria according to", hiddenWord: "Endosymbiosis", sentenceAfter: "theory." },
  { id: 5, sentenceBefore: "In plant cells, Golgi bodies are often called", hiddenWord: "Dictyosomes", sentenceAfter: ", involved in cell wall formation." },
  { id: 6, sentenceBefore: "DNA wraps around proteins called", hiddenWord: "Histones", sentenceAfter: "to form nucleosomes." },
  { id: 7, sentenceBefore: "Red blood cells placed in a hypotonic solution will gain water and", hiddenWord: "Explode", sentenceAfter: "." },
  { id: 8, sentenceBefore: "The glucose ring structure is specifically known as the", hiddenWord: "Haworth", sentenceAfter: "projection." },
  { id: 9, sentenceBefore: "Movement of water across a semipermeable membrane is called", hiddenWord: "Osmosis", sentenceAfter: "." },
  // Previously Added Questions
  { id: 10, sentenceBefore: "", hiddenWord: "Cyanobacteria", sentenceAfter: "were formerly called blue-green algae and contain chlorophyll." },
  { id: 11, sentenceBefore: "", hiddenWord: "Protozoa", sentenceAfter: "are animal-like protists that lack chlorophyll." },
  { id: 12, sentenceBefore: "", hiddenWord: "Arthropods", sentenceAfter: "include more different species than all other animal groups combined." },
  { id: 13, sentenceBefore: "Proteins are polymers of amino acids linked by", hiddenWord: "Peptide", sentenceAfter: "bonds." },
  { id: 14, sentenceBefore: "Enzymes and substrates interact according to the", hiddenWord: "Lock", sentenceAfter: "and key model." },
  { id: 15, sentenceBefore: "Unsaturated fats are usually", hiddenWord: "Liquid", sentenceAfter: "at room temperature." },
  { id: 16, sentenceBefore: "The cell membrane structure is described as the", hiddenWord: "Fluid", sentenceAfter: "Mosaic Model." },
  { id: 17, sentenceBefore: "Rough ER is rough because its surface is studded with", hiddenWord: "Ribosomes", sentenceAfter: "." },
  { id: 18, sentenceBefore: "Lysosomes contain powerful", hiddenWord: "Hydrolytic", sentenceAfter: "enzymes to digest large molecules." },
  { id: 19, sentenceBefore: "Mitochondria are the power plants of the cell, producing", hiddenWord: "ATP", sentenceAfter: "." },
  { id: 20, sentenceBefore: "The", hiddenWord: "Nucleolus", sentenceAfter: "is the site within the nucleus where rRNA is synthesized." },
  { id: 21, sentenceBefore: "", hiddenWord: "Apical", sentenceAfter: "meristems are responsible for primary growth (length) in plants." },
  { id: 22, sentenceBefore: "Ionic bonds involve the complete", hiddenWord: "Transfer", sentenceAfter: "of an electron from one atom to another." },
  // New Set of 30 Questions
  { id: 23, sentenceBefore: "Viruses are considered non-living because they strictly require a host to", hiddenWord: "Reproduce", sentenceAfter: "." },
  { id: 24, sentenceBefore: "Bacteria use whip-like structures called", hiddenWord: "Flagella", sentenceAfter: "for rotary motion." },
  { id: 25, sentenceBefore: "Bacteria that cause disease are classified as", hiddenWord: "Pathogenic", sentenceAfter: "." },
  { id: 26, sentenceBefore: "Plant-like protists containing chlorophyll are known as", hiddenWord: "Algae", sentenceAfter: "." },
  { id: 27, sentenceBefore: "", hiddenWord: "Yeast", sentenceAfter: "is the only example of a unicellular fungus." },
  { id: 28, sentenceBefore: "", hiddenWord: "Xylem", sentenceAfter: "tissue transports water and minerals from the soil up." },
  { id: 29, sentenceBefore: "", hiddenWord: "Phloem", sentenceAfter: "tissue distributes photosynthetic products throughout the plant." },
  { id: 30, sentenceBefore: "", hiddenWord: "Angiosperms", sentenceAfter: "are the group of plants that produce flowers." },
  { id: 31, sentenceBefore: "", hiddenWord: "Insects", sentenceAfter: "represent the largest subgroup of Arthropods." },
  { id: 32, sentenceBefore: "", hiddenWord: "Molluscs", sentenceAfter: "are soft-bodied animals that usually possess a shell." },
  { id: 33, sentenceBefore: "Coelenterates possess a sac-like body with only one", hiddenWord: "Opening", sentenceAfter: "." },
  { id: 34, sentenceBefore: "Vertebrates are a subgroup of Chordates that possess a", hiddenWord: "Backbone", sentenceAfter: "." },
  { id: 35, sentenceBefore: "Compounds containing only Carbon and Hydrogen are called", hiddenWord: "Hydrocarbons", sentenceAfter: "." },
  { id: 36, sentenceBefore: "Compounds with the same formula but different structures are called", hiddenWord: "Isomers", sentenceAfter: "." },
  { id: 37, sentenceBefore: "Plant cell walls are made of the polysaccharide", hiddenWord: "Cellulose", sentenceAfter: "." },
  { id: 38, sentenceBefore: "In animals, glucose is stored as", hiddenWord: "Glycogen", sentenceAfter: "." },
  { id: 39, sentenceBefore: "A triglyceride consists of one glycerol and three", hiddenWord: "Fatty", sentenceAfter: "acids." },
  { id: 40, sentenceBefore: "Saturated fats contain no", hiddenWord: "Double", sentenceAfter: "bonds between carbon atoms." },
  { id: 41, sentenceBefore: "Proteins combined with non-protein groups are called", hiddenWord: "Conjugated", sentenceAfter: "proteins." },
  { id: 42, sentenceBefore: "The non-protein part of a conjugated protein is called a", hiddenWord: "Prosthetic", sentenceAfter: "group." },
  { id: 43, sentenceBefore: "A nucleotide consists of a base, a phosphate, and a 5-carbon", hiddenWord: "Sugar", sentenceAfter: "." },
  { id: 44, sentenceBefore: "In RNA, the base", hiddenWord: "Uracil", sentenceAfter: "replaces Thymine." },
  { id: 45, sentenceBefore: "DNA strands are held together by", hiddenWord: "Hydrogen", sentenceAfter: "bonds." },
  { id: 46, sentenceBefore: "The", hiddenWord: "Smooth", sentenceAfter: "ER is the site of lipid biosynthesis." },
  { id: 47, sentenceBefore: "The nuclear", hiddenWord: "Envelope", sentenceAfter: "is a double membrane surrounding the nucleus." },
  { id: 48, sentenceBefore: "", hiddenWord: "Chromosomes", sentenceAfter: "are the most obvious evidence of DNA organization in the nucleus." },
  { id: 49, sentenceBefore: "", hiddenWord: "Peroxisomes", sentenceAfter: "contain catalase to break down hydrogen peroxide." },
  { id: 50, sentenceBefore: "The", hiddenWord: "Cytoskeleton", sentenceAfter: "anchors organelles and supports cell shape." },
  { id: 51, sentenceBefore: "Microtubules are composed of the protein", hiddenWord: "Tubulin", sentenceAfter: "." },
  { id: 52, sentenceBefore: "Active transport moves solutes against a concentration", hiddenWord: "Gradient", sentenceAfter: "." }
];

export const MONOCOT_DICOT_ITEMS: DragItem[] = [
  { id: 'm1', label: 'One Cotyledon', type: 'monocot' },
  { id: 'd1', label: 'Two Cotyledons', type: 'dicot' },
  { id: 'm2', label: 'Parallel Veins', type: 'monocot' },
  { id: 'd2', label: 'Netlike Veins', type: 'dicot' },
  { id: 'm3', label: 'Floral Parts in 3s', type: 'monocot' },
  { id: 'd3', label: 'Floral Parts in 4s or 5s', type: 'dicot' },
  { id: 'm4', label: 'Fibrous Root System', type: 'monocot' },
  { id: 'd4', label: 'Taproot System', type: 'dicot' },
];

export const PROTISTA_PAIRS: ProtistaMatch[] = [
  { id: 1, organism: 'Amoeba', method: 'Pseudopodia' },
  { id: 2, organism: 'Paramecium', method: 'Cilia' },
  { id: 3, organism: 'Euglena', method: 'Flagella' },
];